### ISSUE TITLE
Getting Started with Geografun

### ISSUE THREAD

**Issue by sharonpamela** [sharonpamela/Project-GeographFun#2]
- create HTML intro page
- capture username and city

## Acceptance Criteria 
- [x] working HTML landing page that captures username and city and turns that into a personalized greeting on the main page

**Comment by doyBrian** [comment]
Intro page is working and is able to capture user input for name and state. Changed from city to state to simplify entry. Since our target users will be mostly children, it is safer to use state than specific city for giving location.
