### ISSUE TITLE
Map Teaser

### ISSUE THREAD

**Issue by sharonpamela** [sharonpamela/Project-GeographFun#3]
- After user enters name and city, they are pushed to the next page where there is a map. 
- There is also a greeting with their name and city entered in previous page. 
- There is also a search box (drop down style) on this that allows a user to search for a country not on the map
- Once the user clicks on a predefined location on the map or searches, they get send to the third and last page that displays the information and interactive facts (related to the location in question)

## Acceptance Criteria

- [x] map page with a map that the user can interact with by selecting some initial locations
- [x] a working search dropdown that allows users to select a country 
- [x]  a Big search button to start interactive fact game about that location
- [x] show the concurrent number of users looking at the page alongside user

**Comment by doyBrian** [comment]
Map page completed and functioning. It is interactive. User can click once to zoom in or out of the chosen country. This will eliminate dropdown menu or search buttons previously planned. I have incorporated Firebase to display number of users accessing the site.
