### ISSUE TITLE
game-page 

### ISSUE THREAD

**Issue by sharonpamela** [sharonpamela/Project-GeographFun#5]
This is the third and last page where we display all of the facts in an interactive way about the location chosen

## Acceptance Criteria ##

- [x] a page with working buttons about all of the facts agreed upon as stated below:
- [x] Weather
- [x] Time
- [ ] How far is it from current location?
- [x] Population
- [x] Flag
- [ ] Func fact?
- [x] Languages
- [x] Capital

- [x]  clicking these buttons will produce some kind of animation on the page and this animation may vary from button to button

**Comment by doyBrian** [comment]
Was not able to implement distance from current location to country selected and fun facts/games. We can propose those features as future development.
